INSERT INTO lernia.locations (city, country, cost_of_living) VALUES
    ('Cambridge', 'United Kingdom', 1650),
    ('Lausanne', 'Switzerland', 1700),
    ('Leuven', 'Belgium', 1200),
    ('Munich', 'Germany', 1600),
    ('Delft', 'Netherlands', 1350);

INSERT INTO lernia.universities (
    name,
    description,
    location_id,
    contact_info,
    website,
    address,
    logo,
    student_count,
    founded_year
) VALUES
    (
        'University of Cambridge',
        'Collegiate research university renowned for excellence in the sciences, arts, and humanities.',
        (SELECT id FROM lernia.locations WHERE city = 'Cambridge' AND country = 'United Kingdom'),
        '+44-1223-337733',
        'https://www.cam.ac.uk',
        'The Old Schools, Trinity Lane, Cambridge CB2 1TN, United Kingdom',
        'https://lernia-s3.s3.eu-north-1.amazonaws.com/cambridge.png',
        20800,
        1209
    ),
    (
        'École Polytechnique Fédérale de Lausanne',
        'Swiss federal institute of technology specializing in engineering and natural sciences.',
        (SELECT id FROM lernia.locations WHERE city = 'Lausanne' AND country = 'Switzerland'),
        '+41-21-693-11-11',
        'https://www.epfl.ch',
        'Route Cantonale, 1015 Lausanne, Switzerland',
        'https://lernia-s3.s3.eu-north-1.amazonaws.com/epfl.png',
        12000,
        1853
    ),
    (
        'KU Leuven',
        'Historic research university offering a broad academic portfolio with strong industry ties.',
        (SELECT id FROM lernia.locations WHERE city = 'Leuven' AND country = 'Belgium'),
        '+32-16-32-40-10',
        'https://www.kuleuven.be',
        'Oude Markt 13, 3000 Leuven, Belgium',
        'https://lernia-s3.s3.eu-north-1.amazonaws.com/ku_leuven.png',
        60300,
        1425
    ),
    (
        'Technical University of Munich',
        'Germany''s entrepreneurial university with strengths in engineering, medicine, and life sciences.',
        (SELECT id FROM lernia.locations WHERE city = 'Munich' AND country = 'Germany'),
        '+49-89-289-01',
        'https://www.tum.de',
        'Arcisstraße 21, 80333 München, Germany',
        'https://lernia-s3.s3.eu-north-1.amazonaws.com/tum.png',
        49000,
        1868
    ),
    (
        'Delft University of Technology',
        'Leading Dutch technical university focused on engineering, design, and innovation.',
        (SELECT id FROM lernia.locations WHERE city = 'Delft' AND country = 'Netherlands'),
        '+31-15-278-9111',
        'https://www.tudelft.nl',
        'Mekelweg 5, 2628 CD Delft, Netherlands',
        'https://lernia-s3.s3.eu-north-1.amazonaws.com/tu_delft.png',
        27000,
        1842
    );

INSERT INTO lernia.courses (
    university_id,
    name,
    description,
    course_type,
    is_remote,
    min_admission_grade,
    cost,
    duration,
    credits,
    language,
    start_date,
    application_deadline,
    contact_email,
    website
) VALUES
    (
        (SELECT id FROM lernia.universities WHERE name = 'University of Cambridge'),
        'BA (Hons) Natural Sciences',
        'Flexible interdisciplinary science programme across physics, biology, and chemistry.',
        'BACHELOR',
        false,
        92,
        9250,
        3,
        180,
        'English',
        '2025-10-01',
        '2024-10-15',
        'ug-admissions@cam.ac.uk',
        'https://www.undergraduate.study.cam.ac.uk/courses/natural-sciences'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'University of Cambridge'),
        'MPhil Machine Learning and Machine Intelligence',
        'Advanced postgraduate course covering modern machine learning theory and practice.',
        'MASTER',
        false,
        90,
        13500,
        1,
        90,
        'English',
        '2025-10-01',
        '2025-01-05',
        'mphil-mlmi@eng.cam.ac.uk',
        'https://www.mlmi.eng.cam.ac.uk/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'University of Cambridge'),
        'PhD Engineering',
        'Doctoral research degree with supervision across all branches of engineering.',
        'DOCTORATE',
        false,
        94,
        0,
        4,
        240,
        'English',
        '2025-10-01',
        '2025-04-30',
        'phd-admissions@eng.cam.ac.uk',
        'https://www.postgraduate.study.cam.ac.uk/courses/directory/egegpdpen'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'École Polytechnique Fédérale de Lausanne'),
        'Bachelor in Communication Systems',
        'Undergraduate programme covering computing, networks, and signal processing.',
        'BACHELOR',
        false,
        88,
        1560,
        3,
        180,
        'French',
        '2025-09-15',
        '2025-04-30',
        'admissions@epfl.ch',
        'https://www.epfl.ch/education/bachelor/programs/communication-systems/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'École Polytechnique Fédérale de Lausanne'),
        'Master in Robotics',
        'Specialised master''s covering robotics systems, perception, and control.',
        'MASTER',
        true,
        87,
        1560,
        2,
        120,
        'English',
        '2025-09-15',
        '2025-12-15',
        'master-robotics@epfl.ch',
        'https://www.epfl.ch/education/master/programs/robotics/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'École Polytechnique Fédérale de Lausanne'),
        'PhD Materials Science',
        'Doctoral programme exploring advanced materials, nanotechnology, and energy systems.',
        'DOCTORATE',
        false,
        90,
        0,
        4,
        240,
        'English',
        '2025-09-15',
        '2025-05-31',
        'phd-materials@epfl.ch',
        'https://www.epfl.ch/education/phd/edmx-materials-science/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'KU Leuven'),
        'Bachelor of Business Engineering',
        'Undergraduate programme mixing business administration with data-driven engineering.',
        'BACHELOR',
        false,
        80,
        980,
        3,
        180,
        'English',
        '2025-09-16',
        '2025-03-01',
        'apply@kuleuven.be',
        'https://www.kuleuven.be/english/education/e_programmes/business-engineering'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'KU Leuven'),
        'Master of Artificial Intelligence',
        'Renowned multidisciplinary master covering cognitive science, robotics, and ML.',
        'MASTER',
        true,
        85,
        6260,
        1,
        60,
        'English',
        '2025-09-16',
        '2025-05-01',
        'ai@kuleuven.be',
        'https://www.kuleuven.be/english/education/Education_and_science/master-of-artificial-intelligence'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'KU Leuven'),
        'PhD Biomedical Sciences',
        'Doctoral training within KU Leuven''s Biomedical Sciences Group.',
        'DOCTORATE',
        false,
        86,
        0,
        4,
        240,
        'English',
        '2025-09-16',
        '2025-06-01',
        'phd-biomedsci@kuleuven.be',
        'https://gbiomed.kuleuven.be/english/phd'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'Technical University of Munich'),
        'BSc Informatics',
        'Industry-oriented informatics programme focusing on software engineering and data systems.',
        'BACHELOR',
        false,
        82,
        144,
        3,
        180,
        'German',
        '2025-10-01',
        '2025-07-15',
        'studium@tum.de',
        'https://www.tum.de/studium/studienangebot/detail/informatik-bachelor'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'Technical University of Munich'),
        'Master in Data Engineering and Analytics',
        'Graduate programme focused on large-scale data processing, analytics, and ML.',
        'MASTER',
        true,
        85,
        144,
        2,
        120,
        'English',
        '2025-10-01',
        '2025-05-31',
        'dea@tum.de',
        'https://www.tum.de/studium/studienangebot/detail/data-engineering-and-analytics-master'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'Technical University of Munich'),
        'PhD Life Sciences',
        'Doctoral degree carried out within the TUM Graduate School''s life sciences faculty.',
        'DOCTORATE',
        false,
        87,
        0,
        4,
        240,
        'English',
        '2025-10-01',
        '2025-06-30',
        'phd-lifesciences@tum.de',
        'https://www.gs.tum.de/en/phd/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'Delft University of Technology'),
        'BSc Aerospace Engineering',
        'International bachelor programme focused on aircraft, spacecraft, and propulsion systems.',
        'BACHELOR',
        false,
        84,
        2314,
        3,
        180,
        'English',
        '2025-09-01',
        '2025-04-01',
        'study@tudelft.nl',
        'https://www.tudelft.nl/en/ae/education/bachelor-of-science/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'Delft University of Technology'),
        'MSc Sustainable Energy Technology',
        'Multidisciplinary master on energy conversion, storage, and smart grids.',
        'MASTER',
        true,
        83,
        1830,
        2,
        120,
        'English',
        '2025-09-01',
        '2025-04-01',
        'set-msc@tudelft.nl',
        'https://www.tudelft.nl/en/education/programmes/masters/sustainable-energy-technology/'
    ),
    (
        (SELECT id FROM lernia.universities WHERE name = 'Delft University of Technology'),
        'PhD Civil Engineering and Geosciences',
        'Doctoral research within TU Delft''s Faculty of Civil Engineering & Geosciences.',
        'DOCTORATE',
        false,
        85,
        0,
        4,
        240,
        'English',
        '2025-09-01',
        '2025-05-15',
        'ceg-phd@tudelft.nl',
        'https://www.tudelft.nl/en/ceg/education/phd'
    );

INSERT INTO lernia.scholarships (university_id, name, description, amount, course_type) VALUES
    ((SELECT id FROM lernia.universities WHERE name = 'University of Cambridge'), 'Gates Cambridge Scholarship', 'Full-cost scholarship for outstanding postgraduate students.', 35000, 'MASTER'),
    ((SELECT id FROM lernia.universities WHERE name = 'École Polytechnique Fédérale de Lausanne'), 'EPFL Excellence Fellowship', 'Merit-based support for master''s students.', 10000, 'MASTER'),
    ((SELECT id FROM lernia.universities WHERE name = 'KU Leuven'), 'Leuven Global Minds Fund', 'Supports doctoral researchers from partner institutions.', 12000, 'DOCTORATE'),
    ((SELECT id FROM lernia.universities WHERE name = 'Technical University of Munich'), 'Deutschlandstipendium TUM', 'Public-private scholarship for talented students.', 3600, 'BACHELOR'),
    ((SELECT id FROM lernia.universities WHERE name = 'Delft University of Technology'), 'Justus & Louise van Effen Excellence Scholarship', 'Scholarship for high-achieving MSc students.', 30000, 'MASTER');

INSERT INTO lernia.users (name, username, email, password, age, gender, location, profile_picture, job_title, creation_date, user_role, premium_start_date) VALUES
    ('Alice Green', 'agreen', 'alice.green@example.com', '$2y$10$5TkGtbvc64nU7P7UcZdtveIJ4CR8p9V094f/b4ckSZw0BaqQ/QsJe', 28, 'FEMALE', 'Cambridge, United Kingdom', 'agreen.png', 'Research Analyst', CURRENT_DATE, 'PREMIUM', '2025-01-01'),
    ('Bastien Martin', 'bmartin', 'bastien.martin@example.com', '$2y$10$5TkGtbvc64nU7P7UcZdtveIJ4CR8p9V094f/b4ckSZw0BaqQ/QsJe', 30, 'MALE', 'Lausanne, Switzerland', 'bmartin.png', 'Robotics Engineer', CURRENT_DATE, 'REGULAR', NULL),
    ('Charlotte Janssen', 'cjanssen', 'charlotte.janssen@example.com', '$2y$10$5TkGtbvc64nU7P7UcZdtveIJ4CR8p9V094f/b4ckSZw0BaqQ/QsJe', 26, 'FEMALE', 'Leuven, Belgium', 'cjanssen.png', 'Business Analyst', CURRENT_DATE, 'PREMIUM', '2024-11-12'),
    ('Gregor Weiss', 'gweiss', 'gregor.weiss@example.com', '$2y$10$5TkGtbvc64nU7P7UcZdtveIJ4CR8p9V094f/b4ckSZw0BaqQ/QsJe', 32, 'MALE', 'Munich, Germany', 'gweiss.png', 'Data Engineer', CURRENT_DATE, 'REGULAR', NULL),
    ('Iris van Dijk', 'ivandijk', 'iris.vandijk@example.com', '$2y$10$5TkGtbvc64nU7P7UcZdtveIJ4CR8p9V094f/b4ckSZw0BaqQ/QsJe', 27, 'FEMALE', 'Delft, Netherlands', 'ivandijk.png', 'Sustainability Consultant', CURRENT_DATE, 'STUDENT', NULL),
    ('Luca Romano', 'lromano', 'luca.romano@example.com', '$2y$10$5TkGtbvc64nU7P7UcZdtveIJ4CR8p9V094f/b4ckSZw0BaqQ/QsJe', 35, 'MALE', 'Milan, Italy', 'lromano.png', 'Civil Engineer', CURRENT_DATE, 'PREMIUM', '2024-09-01');

INSERT INTO lernia.user_bookmarked_universities (user_id, university_id) VALUES
    ((SELECT id FROM lernia.users WHERE username = 'agreen'), (SELECT id FROM lernia.universities WHERE name = 'University of Cambridge')),
    ((SELECT id FROM lernia.users WHERE username = 'bmartin'), (SELECT id FROM lernia.universities WHERE name = 'École Polytechnique Fédérale de Lausanne')),
    ((SELECT id FROM lernia.users WHERE username = 'ivandijk'), (SELECT id FROM lernia.universities WHERE name = 'Delft University of Technology'));

INSERT INTO lernia.user_bookmarked_courses (user_id, course_id) VALUES
    ((SELECT id FROM lernia.users WHERE username = 'agreen'), (SELECT id FROM lernia.courses WHERE name = 'MPhil Machine Learning and Machine Intelligence')),
    ((SELECT id FROM lernia.users WHERE username = 'bmartin'), (SELECT id FROM lernia.courses WHERE name = 'Master in Robotics')),
    ((SELECT id FROM lernia.users WHERE username = 'gweiss'), (SELECT id FROM lernia.courses WHERE name = 'Master in Data Engineering and Analytics')),
    ((SELECT id FROM lernia.users WHERE username = 'ivandijk'), (SELECT id FROM lernia.courses WHERE name = 'MSc Sustainable Energy Technology'));
